[package]
name = "aetherchart"
version = "0.0.0"
authors = ["Mateusz Cegie≈Çka <mateusz@cegla.net>"]
edition = "2018"

[dependencies]
once_cell = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = "2.0"

[[bin]]
name = "aetherchart-merge"
path = "src/merge.rs"
